
server:
  port: 0
  error:
    include-message: always

#Configuracion de spring
spring:
  application:
    name: students-ms
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://hattie.db.elephantsql.com:5432/eadutijg?socketTimeout=3
    username: eadutijg
    password: 1INfITAPVl4SG3KDwsEOi2dIXwwz9inX
    driverClassName: org.postgresql.Driver


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}



